// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8niKGMczpMxCd6nElksWVtDoqhJ5GKE',
    appId: '1:114579535220:web:d30c26de05549b3a33e821',
    messagingSenderId: '114579535220',
    projectId: 'webworksmachinetask',
    authDomain: 'webworksmachinetask.firebaseapp.com',
    storageBucket: 'webworksmachinetask.firebasestorage.app',
    measurementId: 'G-F8K0C555EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQKCqZG74OPxSNFqQ0vqaao8jS7Z7uoso',
    appId: '1:114579535220:android:635bf65b5bbff75e33e821',
    messagingSenderId: '114579535220',
    projectId: 'webworksmachinetask',
    storageBucket: 'webworksmachinetask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpx9HOGZTWU5lxu0CTis8DQqEtbw64bbc',
    appId: '1:114579535220:ios:dcf845120fc5b6a233e821',
    messagingSenderId: '114579535220',
    projectId: 'webworksmachinetask',
    storageBucket: 'webworksmachinetask.firebasestorage.app',
    iosBundleId: 'com.example.webworkTask',
  );
}
